angular.module('ABS', ['ui.bootstrap', 'ui.router', 'ngCookies', 'pascalprecht.translate', 'chart.js']).config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('en', {
        // default
        '《': ' «',
        '》': '»'
    });
    $translateProvider.translations('zh', {
        ':':                                                       '：',
        ',':                                                       '，',
        'OK':                                                      '确认',
        'Cancel':                                                  '取消',
        'Back':                                                    '返回',
        'Update':                                                  '更新',
        'Delete':                                                  '删除',
        'Status':                                                  '状态',
        'Logout':                                                  '登出',
        'Display':                                                 '显示',
        'Date':                                                    '日期',
        'Books':                                                   '图书',
        'Incomes':                                                 '收入',
        'Outgoings':                                               '支出',
        'Orders':                                                  '订单',
        'Order':                                                   '订单',
        'Bills':                                                   '账单',
        'Admin':                                                   '管理',
        'Search':                                                  '查询',
        'Title':                                                   '书名',
        'Authors':                                                 '作者',
        'Price':                                                   '价格',
        'Selling Price':                                           '售价',
        'Amount':                                                  '总量',
        'Total':                                                   '总价',
        'Details':                                                 '详情',
        'Stock':                                                   '库存',
        'Add':                                                     '添加',
        'Put On Shelf':                                            '上架',
        'Password':                                                '密码',
        'Real Name':                                               '姓名',
        'Work ID':                                                 '工号',
        'Age':                                                     '年龄',
        'Gender':                                                  '性别',
        'User Name':                                               '用户名',
        'Sale Amount':                                             '售出量',
        'On Shelf':                                                '已上架',
        'Off Shelf':                                               '未上架',
        'Order ID':                                                '订单号',
        'Order Price':                                             '订购价',
        'Publisher':                                               '出版商',
        'No result found':                                         '无结果',
        'Waiting for Payment':                                     '待支付',
        'Current user':                                            '当前用户',
        'Profile':                                                 '个人信息',
        'User info':                                               '个人信息',
        'Edit Book':                                               '编辑图书',
        'Payment':                                                 '付款状态',
        'Finish Payment':                                          '完成付款',
        'Cancel Order':                                            '取消订单',
        'Current Stock':                                           '当前库存',
        'Order Amount':                                            '订购数量',
        'Related Orders':                                          '相关订单',
        'Related Sales':                                           '相关销售',
        'Edit Details':                                            '编辑信息',
        'Back to List':                                            '返回列表',
        'Add New Books':                                           '添加新书',
        'Add New Order':                                           '创建订单',
        'Sort by amount':                                          '按金额排序',
        'Add New Users':                                           '添加新用户',
        'Payment processed':                                       '已处理付款',
        'You can search ISBN, title, author or publisher.':        '支持搜索 ISBN、标题、作者以及出版社等',
        'Please process your payment as soon as possible.':        '请您尽快完成订单的支付',
        'Attention! Books have not been added to stock yet.':      '注意！此次进货的书目还未上架',
        'Congratulations! The order has been completed.':          '恭喜您，此订单已完成',
        'Payment processed & Off shelf':                           '已完成付款，还未上架',

        // Dates
        'Today':        '今天',
        'Yesterday':    '昨天',
        'Last 7 Days':  '7 天内',
        'Last 30 Days': '30 天内',
        'This Month':   '本月',
        'Last Month':   '上个月',
        'From':         '自',
        'To':           '至',
        'Custom':       '自定区间',
        'Sun':          '日',
        'Mon':          '一',
        'Tue':          '二',
        'Wed':          '三',
        'Thu':          '四',
        'Fri':          '五',
        'Sat':          '六',
        'January':      '一月',
        'February':     '二月',
        'March':        '三月',
        'April':        '四月',
        'May':          '五月',
        'June':         '六月',
        'July':         '七月',
        'August':       '八月',
        'September':    '九月',
        'October':      '十月',
        'November':     '十一月',
        'December':     '十二月'
    });
    $translateProvider.preferredLanguage('zh');

}]);